# Generated by sgb2ns, sgb2ns created by Polly Huang
# GRAPH (#nodes #edges id uu vv ww xx yy zz):
# 50 434 geo(0,{50,100,3,0.200,0.250,75.000}) 100 

set ns [new MultiSim]
# VERTICES (index name u v w x y z):
set n0 [$ns node]
set n1 [$ns node]
set n2 [$ns node]
set n3 [$ns node]
set n4 [$ns node]
set n5 [$ns node]
set n6 [$ns node]
set n7 [$ns node]
set n8 [$ns node]
set n9 [$ns node]
set n10 [$ns node]
set n11 [$ns node]
set n12 [$ns node]
set n13 [$ns node]
set n14 [$ns node]
set n15 [$ns node]
set n16 [$ns node]
set n17 [$ns node]
set n18 [$ns node]
set n19 [$ns node]
set n20 [$ns node]
set n21 [$ns node]
set n22 [$ns node]
set n23 [$ns node]
set n24 [$ns node]
set n25 [$ns node]
set n26 [$ns node]
set n27 [$ns node]
set n28 [$ns node]
set n29 [$ns node]
set n30 [$ns node]
set n31 [$ns node]
set n32 [$ns node]
set n33 [$ns node]
set n34 [$ns node]
set n35 [$ns node]
set n36 [$ns node]
set n37 [$ns node]
set n38 [$ns node]
set n39 [$ns node]
set n40 [$ns node]
set n41 [$ns node]
set n42 [$ns node]
set n43 [$ns node]
set n44 [$ns node]
set n45 [$ns node]
set n46 [$ns node]
set n47 [$ns node]
set n48 [$ns node]
set n49 [$ns node]

set f [open out.tr w]
$ns trace-all $f

# EDGES (from-node to-node length a b):
$ns duplex-link-of-interfaces $n0 $n43 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n0 $n42 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n0 $n40 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n0 $n30 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n0 $n23 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n0 $n3 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n0 $n1 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n1 $n40 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n1 $n34 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n1 $n33 1.5Mb 900ms DropTail
$ns duplex-link-of-interfaces $n1 $n26 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n1 $n25 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n1 $n21 1.5Mb 60ms DropTail
$ns duplex-link-of-interfaces $n1 $n12 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n2 $n42 1.5Mb 1100ms DropTail
$ns duplex-link-of-interfaces $n2 $n27 1.5Mb 910ms DropTail
$ns duplex-link-of-interfaces $n2 $n22 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n2 $n15 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n2 $n12 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n2 $n9 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n2 $n7 1.5Mb 850ms DropTail
$ns duplex-link-of-interfaces $n2 $n4 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n3 $n49 1.5Mb 120ms DropTail
$ns duplex-link-of-interfaces $n3 $n41 1.5Mb 890ms DropTail
$ns duplex-link-of-interfaces $n3 $n29 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n3 $n20 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n3 $n18 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n3 $n12 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n3 $n9 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n3 $n8 1.5Mb 110ms DropTail
$ns duplex-link-of-interfaces $n4 $n48 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n4 $n46 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n4 $n41 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n4 $n33 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n4 $n23 1.5Mb 730ms DropTail
$ns duplex-link-of-interfaces $n4 $n22 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n4 $n12 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n4 $n10 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n4 $n7 1.5Mb 80ms DropTail
$ns duplex-link-of-interfaces $n5 $n45 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n5 $n44 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n5 $n42 1.5Mb 820ms DropTail
$ns duplex-link-of-interfaces $n5 $n40 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n5 $n24 1.5Mb 60ms DropTail
$ns duplex-link-of-interfaces $n5 $n21 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n5 $n19 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n5 $n17 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n5 $n10 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n6 $n42 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n6 $n36 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n6 $n24 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n6 $n15 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n6 $n9 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n7 $n46 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n7 $n45 1.5Mb 110ms DropTail
$ns duplex-link-of-interfaces $n7 $n38 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n8 $n46 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n8 $n41 1.5Mb 790ms DropTail
$ns duplex-link-of-interfaces $n8 $n35 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n8 $n24 1.5Mb 50ms DropTail
$ns duplex-link-of-interfaces $n8 $n22 1.5Mb 190ms DropTail
$ns duplex-link-of-interfaces $n8 $n18 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n8 $n12 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n8 $n10 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n9 $n45 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n9 $n40 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n9 $n38 1.5Mb 860ms DropTail
$ns duplex-link-of-interfaces $n9 $n36 1.5Mb 610ms DropTail
$ns duplex-link-of-interfaces $n9 $n22 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n9 $n20 1.5Mb 920ms DropTail
$ns duplex-link-of-interfaces $n10 $n46 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n10 $n45 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n10 $n43 1.5Mb 730ms DropTail
$ns duplex-link-of-interfaces $n10 $n42 1.5Mb 1000ms DropTail
$ns duplex-link-of-interfaces $n10 $n39 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n10 $n34 1.5Mb 920ms DropTail
$ns duplex-link-of-interfaces $n10 $n29 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n10 $n22 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n10 $n17 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n10 $n15 1.5Mb 100ms DropTail
$ns duplex-link-of-interfaces $n11 $n39 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n11 $n35 1.5Mb 850ms DropTail
$ns duplex-link-of-interfaces $n11 $n20 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n11 $n19 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n11 $n14 1.5Mb 750ms DropTail
$ns duplex-link-of-interfaces $n11 $n12 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n12 $n41 1.5Mb 610ms DropTail
$ns duplex-link-of-interfaces $n12 $n38 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n12 $n28 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n12 $n26 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n12 $n25 1.5Mb 190ms DropTail
$ns duplex-link-of-interfaces $n13 $n46 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n13 $n42 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n13 $n41 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n13 $n28 1.5Mb 870ms DropTail
$ns duplex-link-of-interfaces $n13 $n27 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n13 $n25 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n13 $n17 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n13 $n15 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n14 $n38 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n14 $n34 1.5Mb 180ms DropTail
$ns duplex-link-of-interfaces $n14 $n30 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n14 $n15 1.5Mb 1020ms DropTail
$ns duplex-link-of-interfaces $n15 $n44 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n15 $n41 1.5Mb 1020ms DropTail
$ns duplex-link-of-interfaces $n15 $n32 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n15 $n23 1.5Mb 790ms DropTail
$ns duplex-link-of-interfaces $n16 $n47 1.5Mb 90ms DropTail
$ns duplex-link-of-interfaces $n16 $n35 1.5Mb 870ms DropTail
$ns duplex-link-of-interfaces $n16 $n32 1.5Mb 790ms DropTail
$ns duplex-link-of-interfaces $n16 $n29 1.5Mb 180ms DropTail
$ns duplex-link-of-interfaces $n16 $n25 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n17 $n49 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n17 $n47 1.5Mb 380ms DropTail
$ns duplex-link-of-interfaces $n17 $n44 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n17 $n43 1.5Mb 860ms DropTail
$ns duplex-link-of-interfaces $n17 $n35 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n17 $n29 1.5Mb 150ms DropTail
$ns duplex-link-of-interfaces $n17 $n28 1.5Mb 970ms DropTail
$ns duplex-link-of-interfaces $n17 $n23 1.5Mb 970ms DropTail
$ns duplex-link-of-interfaces $n18 $n35 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n18 $n34 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n18 $n31 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n18 $n23 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n18 $n20 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n19 $n49 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n19 $n48 1.5Mb 190ms DropTail
$ns duplex-link-of-interfaces $n19 $n34 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n19 $n30 1.5Mb 610ms DropTail
$ns duplex-link-of-interfaces $n20 $n49 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n20 $n43 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n20 $n39 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n20 $n32 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n20 $n29 1.5Mb 920ms DropTail
$ns duplex-link-of-interfaces $n20 $n28 1.5Mb 100ms DropTail
$ns duplex-link-of-interfaces $n20 $n22 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n21 $n44 1.5Mb 210ms DropTail
$ns duplex-link-of-interfaces $n21 $n39 1.5Mb 650ms DropTail
$ns duplex-link-of-interfaces $n21 $n32 1.5Mb 1010ms DropTail
$ns duplex-link-of-interfaces $n21 $n26 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n22 $n44 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n22 $n40 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n22 $n35 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n22 $n34 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n22 $n33 1.5Mb 380ms DropTail
$ns duplex-link-of-interfaces $n23 $n43 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n23 $n41 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n23 $n28 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n24 $n45 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n24 $n42 1.5Mb 790ms DropTail
$ns duplex-link-of-interfaces $n24 $n40 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n24 $n38 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n24 $n35 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n25 $n49 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n25 $n46 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n25 $n44 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n25 $n41 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n25 $n38 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n25 $n36 1.5Mb 150ms DropTail
$ns duplex-link-of-interfaces $n26 $n49 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n26 $n48 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n26 $n43 1.5Mb 710ms DropTail
$ns duplex-link-of-interfaces $n26 $n35 1.5Mb 740ms DropTail
$ns duplex-link-of-interfaces $n26 $n34 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n26 $n33 1.5Mb 890ms DropTail
$ns duplex-link-of-interfaces $n26 $n31 1.5Mb 900ms DropTail
$ns duplex-link-of-interfaces $n27 $n42 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n27 $n29 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n28 $n40 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n28 $n35 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n29 $n45 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n29 $n39 1.5Mb 380ms DropTail
$ns duplex-link-of-interfaces $n29 $n33 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n29 $n30 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n30 $n47 1.5Mb 650ms DropTail
$ns duplex-link-of-interfaces $n30 $n46 1.5Mb 960ms DropTail
$ns duplex-link-of-interfaces $n30 $n38 1.5Mb 790ms DropTail
$ns duplex-link-of-interfaces $n30 $n37 1.5Mb 930ms DropTail
$ns duplex-link-of-interfaces $n31 $n42 1.5Mb 1010ms DropTail
$ns duplex-link-of-interfaces $n31 $n40 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n31 $n39 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n31 $n34 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n32 $n48 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n32 $n46 1.5Mb 130ms DropTail
$ns duplex-link-of-interfaces $n32 $n44 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n33 $n46 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n33 $n44 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n33 $n43 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n33 $n38 1.5Mb 750ms DropTail
$ns duplex-link-of-interfaces $n33 $n34 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n34 $n47 1.5Mb 810ms DropTail
$ns duplex-link-of-interfaces $n34 $n45 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n34 $n44 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n34 $n43 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n34 $n40 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n34 $n38 1.5Mb 30ms DropTail
$ns duplex-link-of-interfaces $n35 $n45 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n35 $n37 1.5Mb 40ms DropTail
$ns duplex-link-of-interfaces $n36 $n49 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n36 $n45 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n36 $n44 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n36 $n42 1.5Mb 900ms DropTail
$ns duplex-link-of-interfaces $n37 $n48 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n37 $n40 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n37 $n39 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n37 $n38 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n39 $n45 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n39 $n42 1.5Mb 790ms DropTail
$ns duplex-link-of-interfaces $n39 $n41 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n39 $n40 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n40 $n44 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n41 $n47 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n42 $n49 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n43 $n48 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n44 $n49 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n44 $n48 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n46 $n47 1.5Mb 590ms DropTail

set ctrmcastcomp [new CtrMcastComp $ns]
set ctrrpcomp [new CtrRPComp $ns]

set ctrmcast0 [new CtrMcast $ns $n0 $ctrmcastcomp [list 1 1]]
set ctrmcast1 [new CtrMcast $ns $n1 $ctrmcastcomp [list 1 1]]
set ctrmcast2 [new CtrMcast $ns $n2 $ctrmcastcomp [list 1 1]]
set ctrmcast3 [new CtrMcast $ns $n3 $ctrmcastcomp [list 1 1]]
set ctrmcast4 [new CtrMcast $ns $n4 $ctrmcastcomp [list 1 1]]
set ctrmcast5 [new CtrMcast $ns $n5 $ctrmcastcomp [list 1 1]]
set ctrmcast6 [new CtrMcast $ns $n6 $ctrmcastcomp [list 1 1]]
set ctrmcast7 [new CtrMcast $ns $n7 $ctrmcastcomp [list 1 1]]
set ctrmcast8 [new CtrMcast $ns $n8 $ctrmcastcomp [list 1 1]]
set ctrmcast9 [new CtrMcast $ns $n9 $ctrmcastcomp [list 1 1]]
set ctrmcast10 [new CtrMcast $ns $n10 $ctrmcastcomp [list 1 1]]
set ctrmcast11 [new CtrMcast $ns $n11 $ctrmcastcomp [list 1 1]]
set ctrmcast12 [new CtrMcast $ns $n12 $ctrmcastcomp [list 1 1]]
set ctrmcast13 [new CtrMcast $ns $n13 $ctrmcastcomp [list 1 1]]
set ctrmcast14 [new CtrMcast $ns $n14 $ctrmcastcomp [list 1 1]]
set ctrmcast15 [new CtrMcast $ns $n15 $ctrmcastcomp [list 1 1]]
set ctrmcast16 [new CtrMcast $ns $n16 $ctrmcastcomp [list 1 1]]
set ctrmcast17 [new CtrMcast $ns $n17 $ctrmcastcomp [list 1 1]]
set ctrmcast18 [new CtrMcast $ns $n18 $ctrmcastcomp [list 1 1]]
set ctrmcast19 [new CtrMcast $ns $n19 $ctrmcastcomp [list 1 1]]
set ctrmcast20 [new CtrMcast $ns $n20 $ctrmcastcomp [list 1 1]]
set ctrmcast21 [new CtrMcast $ns $n21 $ctrmcastcomp [list 1 1]]
set ctrmcast22 [new CtrMcast $ns $n22 $ctrmcastcomp [list 1 1]]
set ctrmcast23 [new CtrMcast $ns $n23 $ctrmcastcomp [list 1 1]]
set ctrmcast24 [new CtrMcast $ns $n24 $ctrmcastcomp [list 1 1]]
set ctrmcast25 [new CtrMcast $ns $n25 $ctrmcastcomp [list 1 1]]
set ctrmcast26 [new CtrMcast $ns $n26 $ctrmcastcomp [list 1 1]]
set ctrmcast27 [new CtrMcast $ns $n27 $ctrmcastcomp [list 1 1]]
set ctrmcast28 [new CtrMcast $ns $n28 $ctrmcastcomp [list 1 1]]
set ctrmcast29 [new CtrMcast $ns $n29 $ctrmcastcomp [list 1 1]]
set ctrmcast30 [new CtrMcast $ns $n30 $ctrmcastcomp [list 1 1]]
set ctrmcast31 [new CtrMcast $ns $n31 $ctrmcastcomp [list 1 1]]
set ctrmcast32 [new CtrMcast $ns $n32 $ctrmcastcomp [list 1 1]]
set ctrmcast33 [new CtrMcast $ns $n33 $ctrmcastcomp [list 1 1]]
set ctrmcast34 [new CtrMcast $ns $n34 $ctrmcastcomp [list 1 1]]
set ctrmcast35 [new CtrMcast $ns $n35 $ctrmcastcomp [list 1 1]]
set ctrmcast36 [new CtrMcast $ns $n36 $ctrmcastcomp [list 1 1]]
set ctrmcast37 [new CtrMcast $ns $n37 $ctrmcastcomp [list 1 1]]
set ctrmcast38 [new CtrMcast $ns $n38 $ctrmcastcomp [list 1 1]]
set ctrmcast39 [new CtrMcast $ns $n39 $ctrmcastcomp [list 1 1]]
set ctrmcast40 [new CtrMcast $ns $n40 $ctrmcastcomp [list 1 1]]
set ctrmcast41 [new CtrMcast $ns $n41 $ctrmcastcomp [list 1 1]]
set ctrmcast42 [new CtrMcast $ns $n42 $ctrmcastcomp [list 1 1]]
set ctrmcast43 [new CtrMcast $ns $n43 $ctrmcastcomp [list 1 1]]
set ctrmcast44 [new CtrMcast $ns $n44 $ctrmcastcomp [list 1 1]]
set ctrmcast45 [new CtrMcast $ns $n45 $ctrmcastcomp [list 1 1]]
set ctrmcast46 [new CtrMcast $ns $n46 $ctrmcastcomp [list 1 1]]
set ctrmcast47 [new CtrMcast $ns $n47 $ctrmcastcomp [list 1 1]]
set ctrmcast48 [new CtrMcast $ns $n48 $ctrmcastcomp [list 1 1]]
set ctrmcast49 [new CtrMcast $ns $n49 $ctrmcastcomp [list 1 1]]

$ns compute-routes
$ctrrpcomp compute-rpset

set rcvr18 [new Agent/Null]
$ns attach-agent $n18 $rcvr18
$ns at 2 "$n18 join-group $rcvr18 0x8003"
set rcvr37 [new Agent/Null]
$ns attach-agent $n37 $rcvr37
$ns at 3 "$n37 join-group $rcvr37 0x8003"
set rcvr41 [new Agent/Null]
$ns attach-agent $n41 $rcvr41
$ns at 4 "$n41 join-group $rcvr41 0x8003"
set rcvr23 [new Agent/Null]
$ns attach-agent $n23 $rcvr23
$ns at 5 "$n23 join-group $rcvr23 0x8003"
set rcvr17 [new Agent/Null]
$ns attach-agent $n17 $rcvr17
$ns at 6 "$n17 join-group $rcvr17 0x8003"
set rcvr15 [new Agent/Null]
$ns attach-agent $n15 $rcvr15
$ns at 7 "$n15 join-group $rcvr15 0x8003"
set rcvr14 [new Agent/Null]
$ns attach-agent $n14 $rcvr14
$ns at 8 "$n14 join-group $rcvr14 0x8003"
set rcvr47 [new Agent/Null]
$ns attach-agent $n47 $rcvr47
$ns at 9 "$n47 join-group $rcvr47 0x8003"
set rcvr19 [new Agent/Null]
$ns attach-agent $n19 $rcvr19
$ns at 10 "$n19 join-group $rcvr19 0x8003"
set rcvr16 [new Agent/Null]
$ns attach-agent $n16 $rcvr16
$ns at 11 "$n16 join-group $rcvr16 0x8003"

set sender [new Agent/CBR]
$sender set dst_ 0x8003
$sender set class_ 2
$ns attach-agent $n2 $sender

$ns at 0 "$sender start"

# START ns
$ns at 11 "exit 0"
$ns run

