# Generated by sgb2ns, sgb2ns created by Polly Huang
# GRAPH (#nodes #edges id uu vv ww xx yy zz):
# 100 1900 geo(0,{100,100,3,0.200,0.250,75.000}) 100 

set ns [new MultiSim]
# VERTICES (index name u v w x y z):
set n0 [$ns node]
set n1 [$ns node]
set n2 [$ns node]
set n3 [$ns node]
set n4 [$ns node]
set n5 [$ns node]
set n6 [$ns node]
set n7 [$ns node]
set n8 [$ns node]
set n9 [$ns node]
set n10 [$ns node]
set n11 [$ns node]
set n12 [$ns node]
set n13 [$ns node]
set n14 [$ns node]
set n15 [$ns node]
set n16 [$ns node]
set n17 [$ns node]
set n18 [$ns node]
set n19 [$ns node]
set n20 [$ns node]
set n21 [$ns node]
set n22 [$ns node]
set n23 [$ns node]
set n24 [$ns node]
set n25 [$ns node]
set n26 [$ns node]
set n27 [$ns node]
set n28 [$ns node]
set n29 [$ns node]
set n30 [$ns node]
set n31 [$ns node]
set n32 [$ns node]
set n33 [$ns node]
set n34 [$ns node]
set n35 [$ns node]
set n36 [$ns node]
set n37 [$ns node]
set n38 [$ns node]
set n39 [$ns node]
set n40 [$ns node]
set n41 [$ns node]
set n42 [$ns node]
set n43 [$ns node]
set n44 [$ns node]
set n45 [$ns node]
set n46 [$ns node]
set n47 [$ns node]
set n48 [$ns node]
set n49 [$ns node]
set n50 [$ns node]
set n51 [$ns node]
set n52 [$ns node]
set n53 [$ns node]
set n54 [$ns node]
set n55 [$ns node]
set n56 [$ns node]
set n57 [$ns node]
set n58 [$ns node]
set n59 [$ns node]
set n60 [$ns node]
set n61 [$ns node]
set n62 [$ns node]
set n63 [$ns node]
set n64 [$ns node]
set n65 [$ns node]
set n66 [$ns node]
set n67 [$ns node]
set n68 [$ns node]
set n69 [$ns node]
set n70 [$ns node]
set n71 [$ns node]
set n72 [$ns node]
set n73 [$ns node]
set n74 [$ns node]
set n75 [$ns node]
set n76 [$ns node]
set n77 [$ns node]
set n78 [$ns node]
set n79 [$ns node]
set n80 [$ns node]
set n81 [$ns node]
set n82 [$ns node]
set n83 [$ns node]
set n84 [$ns node]
set n85 [$ns node]
set n86 [$ns node]
set n87 [$ns node]
set n88 [$ns node]
set n89 [$ns node]
set n90 [$ns node]
set n91 [$ns node]
set n92 [$ns node]
set n93 [$ns node]
set n94 [$ns node]
set n95 [$ns node]
set n96 [$ns node]
set n97 [$ns node]
set n98 [$ns node]
set n99 [$ns node]

set f [open out.tr w]
$ns trace-all $f

# EDGES (from-node to-node length a b):
$ns duplex-link-of-interfaces $n0 $n98 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n0 $n96 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n0 $n93 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n0 $n90 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n0 $n82 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n0 $n70 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n0 $n61 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n0 $n59 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n0 $n53 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n0 $n50 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n0 $n49 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n0 $n37 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n0 $n22 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n0 $n17 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n0 $n10 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n0 $n7 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n0 $n4 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n0 $n2 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n1 $n99 1.5Mb 1020ms DropTail
$ns duplex-link-of-interfaces $n1 $n90 1.5Mb 610ms DropTail
$ns duplex-link-of-interfaces $n1 $n84 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n1 $n77 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n1 $n76 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n1 $n74 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n1 $n72 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n1 $n56 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n1 $n53 1.5Mb 1130ms DropTail
$ns duplex-link-of-interfaces $n1 $n51 1.5Mb 80ms DropTail
$ns duplex-link-of-interfaces $n1 $n49 1.5Mb 710ms DropTail
$ns duplex-link-of-interfaces $n1 $n42 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n1 $n36 1.5Mb 870ms DropTail
$ns duplex-link-of-interfaces $n1 $n34 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n1 $n29 1.5Mb 380ms DropTail
$ns duplex-link-of-interfaces $n1 $n21 1.5Mb 60ms DropTail
$ns duplex-link-of-interfaces $n1 $n11 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n1 $n10 1.5Mb 890ms DropTail
$ns duplex-link-of-interfaces $n2 $n96 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n2 $n85 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n2 $n83 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n2 $n79 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n2 $n73 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n2 $n71 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n2 $n66 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n2 $n65 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n2 $n58 1.5Mb 930ms DropTail
$ns duplex-link-of-interfaces $n2 $n20 1.5Mb 110ms DropTail
$ns duplex-link-of-interfaces $n2 $n14 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n3 $n96 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n3 $n94 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n3 $n90 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n3 $n89 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n3 $n87 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n3 $n86 1.5Mb 900ms DropTail
$ns duplex-link-of-interfaces $n3 $n83 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n3 $n78 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n3 $n73 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n3 $n66 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n3 $n61 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n3 $n59 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n3 $n50 1.5Mb 180ms DropTail
$ns duplex-link-of-interfaces $n3 $n45 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n3 $n43 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n3 $n41 1.5Mb 890ms DropTail
$ns duplex-link-of-interfaces $n3 $n27 1.5Mb 790ms DropTail
$ns duplex-link-of-interfaces $n3 $n25 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n3 $n11 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n3 $n6 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n4 $n88 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n4 $n87 1.5Mb 130ms DropTail
$ns duplex-link-of-interfaces $n4 $n85 1.5Mb 130ms DropTail
$ns duplex-link-of-interfaces $n4 $n77 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n4 $n75 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n4 $n65 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n4 $n62 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n4 $n52 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n4 $n50 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n4 $n49 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n4 $n26 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n4 $n22 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n4 $n7 1.5Mb 80ms DropTail
$ns duplex-link-of-interfaces $n4 $n6 1.5Mb 90ms DropTail
$ns duplex-link-of-interfaces $n5 $n97 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n5 $n93 1.5Mb 750ms DropTail
$ns duplex-link-of-interfaces $n5 $n79 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n5 $n76 1.5Mb 650ms DropTail
$ns duplex-link-of-interfaces $n5 $n67 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n5 $n58 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n5 $n39 1.5Mb 70ms DropTail
$ns duplex-link-of-interfaces $n5 $n35 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n5 $n31 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n5 $n16 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n5 $n12 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n5 $n8 1.5Mb 110ms DropTail
$ns duplex-link-of-interfaces $n5 $n7 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n6 $n98 1.5Mb 210ms DropTail
$ns duplex-link-of-interfaces $n6 $n73 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n6 $n72 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n6 $n69 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n6 $n61 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n6 $n58 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n6 $n56 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n6 $n54 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n6 $n51 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n6 $n50 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n6 $n42 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n6 $n36 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n6 $n35 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n6 $n30 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n6 $n22 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n6 $n10 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n6 $n7 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n7 $n95 1.5Mb 70ms DropTail
$ns duplex-link-of-interfaces $n7 $n94 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n7 $n93 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n7 $n77 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n7 $n72 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n7 $n65 1.5Mb 650ms DropTail
$ns duplex-link-of-interfaces $n7 $n59 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n7 $n54 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n7 $n48 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n7 $n44 1.5Mb 80ms DropTail
$ns duplex-link-of-interfaces $n7 $n37 1.5Mb 730ms DropTail
$ns duplex-link-of-interfaces $n7 $n34 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n7 $n33 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n7 $n27 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n7 $n25 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n7 $n24 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n7 $n10 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n8 $n98 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n8 $n93 1.5Mb 740ms DropTail
$ns duplex-link-of-interfaces $n8 $n90 1.5Mb 90ms DropTail
$ns duplex-link-of-interfaces $n8 $n88 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n8 $n85 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n8 $n82 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n8 $n80 1.5Mb 60ms DropTail
$ns duplex-link-of-interfaces $n8 $n65 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n8 $n62 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n8 $n60 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n8 $n58 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n8 $n55 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n8 $n38 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n8 $n36 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n8 $n23 1.5Mb 610ms DropTail
$ns duplex-link-of-interfaces $n8 $n13 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n8 $n9 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n9 $n97 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n9 $n96 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n9 $n85 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n9 $n79 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n9 $n73 1.5Mb 710ms DropTail
$ns duplex-link-of-interfaces $n9 $n70 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n9 $n60 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n9 $n55 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n9 $n41 1.5Mb 880ms DropTail
$ns duplex-link-of-interfaces $n9 $n28 1.5Mb 840ms DropTail
$ns duplex-link-of-interfaces $n9 $n26 1.5Mb 610ms DropTail
$ns duplex-link-of-interfaces $n9 $n25 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n9 $n20 1.5Mb 920ms DropTail
$ns duplex-link-of-interfaces $n9 $n12 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n9 $n11 1.5Mb 150ms DropTail
$ns duplex-link-of-interfaces $n9 $n10 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n10 $n95 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n10 $n87 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n10 $n83 1.5Mb 710ms DropTail
$ns duplex-link-of-interfaces $n10 $n81 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n10 $n80 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n10 $n79 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n10 $n76 1.5Mb 900ms DropTail
$ns duplex-link-of-interfaces $n10 $n74 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n10 $n67 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n10 $n65 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n10 $n64 1.5Mb 110ms DropTail
$ns duplex-link-of-interfaces $n10 $n59 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n10 $n55 1.5Mb 650ms DropTail
$ns duplex-link-of-interfaces $n10 $n53 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n10 $n51 1.5Mb 810ms DropTail
$ns duplex-link-of-interfaces $n10 $n49 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n10 $n30 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n10 $n28 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n10 $n27 1.5Mb 930ms DropTail
$ns duplex-link-of-interfaces $n10 $n22 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n10 $n17 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n10 $n16 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n11 $n97 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n11 $n92 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n11 $n91 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n11 $n86 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n11 $n81 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n11 $n72 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n11 $n61 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n11 $n53 1.5Mb 910ms DropTail
$ns duplex-link-of-interfaces $n11 $n50 1.5Mb 210ms DropTail
$ns duplex-link-of-interfaces $n11 $n49 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n11 $n48 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n11 $n35 1.5Mb 850ms DropTail
$ns duplex-link-of-interfaces $n11 $n27 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n11 $n26 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n11 $n25 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n11 $n24 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n11 $n20 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n11 $n19 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n11 $n17 1.5Mb 120ms DropTail
$ns duplex-link-of-interfaces $n12 $n86 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n12 $n80 1.5Mb 110ms DropTail
$ns duplex-link-of-interfaces $n12 $n70 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n12 $n67 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n12 $n38 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n12 $n35 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n12 $n32 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n12 $n29 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n12 $n28 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n12 $n22 1.5Mb 120ms DropTail
$ns duplex-link-of-interfaces $n12 $n21 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n13 $n96 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n13 $n90 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n13 $n89 1.5Mb 730ms DropTail
$ns duplex-link-of-interfaces $n13 $n87 1.5Mb 180ms DropTail
$ns duplex-link-of-interfaces $n13 $n82 1.5Mb 750ms DropTail
$ns duplex-link-of-interfaces $n13 $n74 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n13 $n70 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n13 $n62 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n13 $n59 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n13 $n55 1.5Mb 80ms DropTail
$ns duplex-link-of-interfaces $n13 $n51 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n13 $n48 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n13 $n40 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n13 $n26 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n14 $n95 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n14 $n82 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n14 $n79 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n14 $n73 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n14 $n68 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n14 $n65 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n14 $n62 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n14 $n61 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n14 $n55 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n14 $n50 1.5Mb 820ms DropTail
$ns duplex-link-of-interfaces $n14 $n47 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n14 $n44 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n14 $n40 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n14 $n25 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n14 $n19 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n14 $n18 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n15 $n94 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n15 $n86 1.5Mb 1030ms DropTail
$ns duplex-link-of-interfaces $n15 $n79 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n15 $n78 1.5Mb 1060ms DropTail
$ns duplex-link-of-interfaces $n15 $n70 1.5Mb 950ms DropTail
$ns duplex-link-of-interfaces $n15 $n56 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n15 $n52 1.5Mb 900ms DropTail
$ns duplex-link-of-interfaces $n15 $n50 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n15 $n49 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n15 $n48 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n15 $n45 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n15 $n40 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n15 $n38 1.5Mb 930ms DropTail
$ns duplex-link-of-interfaces $n15 $n36 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n15 $n27 1.5Mb 930ms DropTail
$ns duplex-link-of-interfaces $n16 $n99 1.5Mb 820ms DropTail
$ns duplex-link-of-interfaces $n16 $n98 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n16 $n90 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n16 $n86 1.5Mb 890ms DropTail
$ns duplex-link-of-interfaces $n16 $n81 1.5Mb 380ms DropTail
$ns duplex-link-of-interfaces $n16 $n80 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n16 $n76 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n16 $n75 1.5Mb 840ms DropTail
$ns duplex-link-of-interfaces $n16 $n74 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n16 $n68 1.5Mb 730ms DropTail
$ns duplex-link-of-interfaces $n16 $n61 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n16 $n60 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n16 $n59 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n16 $n58 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n16 $n57 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n16 $n53 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n16 $n41 1.5Mb 880ms DropTail
$ns duplex-link-of-interfaces $n16 $n40 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n16 $n39 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n16 $n38 1.5Mb 840ms DropTail
$ns duplex-link-of-interfaces $n16 $n37 1.5Mb 880ms DropTail
$ns duplex-link-of-interfaces $n16 $n29 1.5Mb 180ms DropTail
$ns duplex-link-of-interfaces $n17 $n97 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n17 $n96 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n17 $n92 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n17 $n88 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n17 $n85 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n17 $n84 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n17 $n81 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n17 $n80 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n17 $n78 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n17 $n69 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n17 $n63 1.5Mb 890ms DropTail
$ns duplex-link-of-interfaces $n17 $n56 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n17 $n52 1.5Mb 740ms DropTail
$ns duplex-link-of-interfaces $n17 $n48 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n17 $n45 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n17 $n42 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n17 $n34 1.5Mb 850ms DropTail
$ns duplex-link-of-interfaces $n17 $n30 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n17 $n28 1.5Mb 970ms DropTail
$ns duplex-link-of-interfaces $n17 $n23 1.5Mb 970ms DropTail
$ns duplex-link-of-interfaces $n17 $n22 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n18 $n97 1.5Mb 130ms DropTail
$ns duplex-link-of-interfaces $n18 $n96 1.5Mb 120ms DropTail
$ns duplex-link-of-interfaces $n18 $n94 1.5Mb 140ms DropTail
$ns duplex-link-of-interfaces $n18 $n92 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n18 $n84 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n18 $n79 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n18 $n77 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n18 $n75 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n18 $n59 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n18 $n56 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n18 $n55 1.5Mb 140ms DropTail
$ns duplex-link-of-interfaces $n18 $n42 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n18 $n41 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n18 $n40 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n18 $n36 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n18 $n28 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n18 $n20 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n19 $n98 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n19 $n95 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n19 $n57 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n19 $n40 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n19 $n37 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n19 $n36 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n19 $n35 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n19 $n29 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n19 $n27 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n19 $n24 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n19 $n23 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n19 $n22 1.5Mb 210ms DropTail
$ns duplex-link-of-interfaces $n20 $n96 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n20 $n94 1.5Mb 650ms DropTail
$ns duplex-link-of-interfaces $n20 $n85 1.5Mb 790ms DropTail
$ns duplex-link-of-interfaces $n20 $n73 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n20 $n70 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n20 $n66 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n20 $n64 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n20 $n63 1.5Mb 840ms DropTail
$ns duplex-link-of-interfaces $n20 $n60 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n20 $n58 1.5Mb 1040ms DropTail
$ns duplex-link-of-interfaces $n20 $n56 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n20 $n54 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n20 $n53 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n20 $n52 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n20 $n48 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n20 $n40 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n20 $n39 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n20 $n38 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n20 $n32 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n20 $n26 1.5Mb 1110ms DropTail
$ns duplex-link-of-interfaces $n20 $n25 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n20 $n22 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n20 $n21 1.5Mb 1140ms DropTail
$ns duplex-link-of-interfaces $n21 $n78 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n21 $n76 1.5Mb 710ms DropTail
$ns duplex-link-of-interfaces $n21 $n74 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n21 $n64 1.5Mb 810ms DropTail
$ns duplex-link-of-interfaces $n21 $n61 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n21 $n60 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n21 $n58 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n21 $n44 1.5Mb 210ms DropTail
$ns duplex-link-of-interfaces $n21 $n42 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n21 $n40 1.5Mb 750ms DropTail
$ns duplex-link-of-interfaces $n21 $n38 1.5Mb 740ms DropTail
$ns duplex-link-of-interfaces $n21 $n33 1.5Mb 850ms DropTail
$ns duplex-link-of-interfaces $n21 $n31 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n21 $n30 1.5Mb 90ms DropTail
$ns duplex-link-of-interfaces $n21 $n29 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n22 $n99 1.5Mb 610ms DropTail
$ns duplex-link-of-interfaces $n22 $n91 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n22 $n84 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n22 $n80 1.5Mb 140ms DropTail
$ns duplex-link-of-interfaces $n22 $n79 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n22 $n74 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n22 $n73 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n22 $n70 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n22 $n62 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n22 $n58 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n22 $n57 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n22 $n34 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n22 $n26 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n23 $n98 1.5Mb 810ms DropTail
$ns duplex-link-of-interfaces $n23 $n96 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n23 $n95 1.5Mb 730ms DropTail
$ns duplex-link-of-interfaces $n23 $n94 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n23 $n89 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n23 $n84 1.5Mb 860ms DropTail
$ns duplex-link-of-interfaces $n23 $n81 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n23 $n78 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n23 $n75 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n23 $n74 1.5Mb 910ms DropTail
$ns duplex-link-of-interfaces $n23 $n71 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n23 $n70 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n23 $n61 1.5Mb 750ms DropTail
$ns duplex-link-of-interfaces $n23 $n56 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n23 $n38 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n23 $n34 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n23 $n31 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n23 $n29 1.5Mb 860ms DropTail
$ns duplex-link-of-interfaces $n23 $n25 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n24 $n82 1.5Mb 740ms DropTail
$ns duplex-link-of-interfaces $n24 $n71 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n24 $n65 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n24 $n58 1.5Mb 650ms DropTail
$ns duplex-link-of-interfaces $n24 $n56 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n24 $n42 1.5Mb 790ms DropTail
$ns duplex-link-of-interfaces $n24 $n41 1.5Mb 750ms DropTail
$ns duplex-link-of-interfaces $n24 $n39 1.5Mb 10ms DropTail
$ns duplex-link-of-interfaces $n24 $n36 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n24 $n33 1.5Mb 190ms DropTail
$ns duplex-link-of-interfaces $n24 $n31 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n24 $n27 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n25 $n95 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n25 $n86 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n25 $n85 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n25 $n81 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n25 $n67 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n25 $n66 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n25 $n60 1.5Mb 70ms DropTail
$ns duplex-link-of-interfaces $n25 $n52 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n25 $n49 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n25 $n41 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n25 $n33 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n25 $n32 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n25 $n30 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n25 $n28 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n25 $n27 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n26 $n96 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n26 $n94 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n26 $n89 1.5Mb 920ms DropTail
$ns duplex-link-of-interfaces $n26 $n88 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n26 $n86 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n26 $n85 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n26 $n76 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n26 $n75 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n26 $n72 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n26 $n56 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n26 $n53 1.5Mb 1010ms DropTail
$ns duplex-link-of-interfaces $n26 $n52 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n26 $n51 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n26 $n38 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n26 $n36 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n26 $n35 1.5Mb 740ms DropTail
$ns duplex-link-of-interfaces $n26 $n32 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n26 $n29 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n26 $n28 1.5Mb 1010ms DropTail
$ns duplex-link-of-interfaces $n26 $n27 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n27 $n99 1.5Mb 750ms DropTail
$ns duplex-link-of-interfaces $n27 $n93 1.5Mb 100ms DropTail
$ns duplex-link-of-interfaces $n27 $n90 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n27 $n84 1.5Mb 150ms DropTail
$ns duplex-link-of-interfaces $n27 $n75 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n27 $n72 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n27 $n65 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n27 $n63 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n27 $n51 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n27 $n49 1.5Mb 710ms DropTail
$ns duplex-link-of-interfaces $n27 $n33 1.5Mb 860ms DropTail
$ns duplex-link-of-interfaces $n27 $n32 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n27 $n31 1.5Mb 820ms DropTail
$ns duplex-link-of-interfaces $n28 $n99 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n28 $n98 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n28 $n97 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n28 $n88 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n28 $n87 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n28 $n84 1.5Mb 1000ms DropTail
$ns duplex-link-of-interfaces $n28 $n81 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n28 $n74 1.5Mb 910ms DropTail
$ns duplex-link-of-interfaces $n28 $n66 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n28 $n55 1.5Mb 790ms DropTail
$ns duplex-link-of-interfaces $n28 $n53 1.5Mb 130ms DropTail
$ns duplex-link-of-interfaces $n28 $n46 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n28 $n41 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n28 $n39 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n28 $n34 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n28 $n29 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n29 $n99 1.5Mb 850ms DropTail
$ns duplex-link-of-interfaces $n29 $n97 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n29 $n96 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n29 $n95 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n29 $n94 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n29 $n84 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n29 $n77 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n29 $n73 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n29 $n72 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n29 $n65 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n29 $n64 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n29 $n63 1.5Mb 850ms DropTail
$ns duplex-link-of-interfaces $n29 $n60 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n29 $n55 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n29 $n46 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n29 $n43 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n29 $n42 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n29 $n39 1.5Mb 380ms DropTail
$ns duplex-link-of-interfaces $n29 $n38 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n29 $n30 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n30 $n98 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n30 $n94 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n30 $n93 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n30 $n91 1.5Mb 880ms DropTail
$ns duplex-link-of-interfaces $n30 $n88 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n30 $n86 1.5Mb 710ms DropTail
$ns duplex-link-of-interfaces $n30 $n82 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n30 $n77 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n30 $n76 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n30 $n72 1.5Mb 610ms DropTail
$ns duplex-link-of-interfaces $n30 $n71 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n30 $n70 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n30 $n64 1.5Mb 900ms DropTail
$ns duplex-link-of-interfaces $n30 $n61 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n30 $n60 1.5Mb 860ms DropTail
$ns duplex-link-of-interfaces $n30 $n46 1.5Mb 960ms DropTail
$ns duplex-link-of-interfaces $n30 $n39 1.5Mb 750ms DropTail
$ns duplex-link-of-interfaces $n30 $n37 1.5Mb 930ms DropTail
$ns duplex-link-of-interfaces $n31 $n96 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n31 $n88 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n31 $n85 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n31 $n82 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n31 $n77 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n31 $n65 1.5Mb 210ms DropTail
$ns duplex-link-of-interfaces $n31 $n58 1.5Mb 840ms DropTail
$ns duplex-link-of-interfaces $n31 $n37 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n31 $n36 1.5Mb 140ms DropTail
$ns duplex-link-of-interfaces $n31 $n35 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n32 $n93 1.5Mb 910ms DropTail
$ns duplex-link-of-interfaces $n32 $n89 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n32 $n74 1.5Mb 910ms DropTail
$ns duplex-link-of-interfaces $n32 $n73 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n32 $n67 1.5Mb 890ms DropTail
$ns duplex-link-of-interfaces $n32 $n65 1.5Mb 190ms DropTail
$ns duplex-link-of-interfaces $n32 $n61 1.5Mb 820ms DropTail
$ns duplex-link-of-interfaces $n32 $n58 1.5Mb 870ms DropTail
$ns duplex-link-of-interfaces $n32 $n57 1.5Mb 90ms DropTail
$ns duplex-link-of-interfaces $n32 $n52 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n32 $n44 1.5Mb 800ms DropTail
$ns duplex-link-of-interfaces $n32 $n41 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n33 $n87 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n33 $n86 1.5Mb 880ms DropTail
$ns duplex-link-of-interfaces $n33 $n83 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n33 $n79 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n33 $n76 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n33 $n75 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n33 $n67 1.5Mb 770ms DropTail
$ns duplex-link-of-interfaces $n33 $n65 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n33 $n61 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n33 $n48 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n33 $n46 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n33 $n44 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n33 $n43 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n34 $n92 1.5Mb 940ms DropTail
$ns duplex-link-of-interfaces $n34 $n75 1.5Mb 70ms DropTail
$ns duplex-link-of-interfaces $n34 $n72 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n34 $n67 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n34 $n64 1.5Mb 820ms DropTail
$ns duplex-link-of-interfaces $n34 $n63 1.5Mb 60ms DropTail
$ns duplex-link-of-interfaces $n34 $n60 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n34 $n58 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n34 $n49 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n34 $n46 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n34 $n40 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n34 $n39 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n34 $n35 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n35 $n98 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n35 $n95 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n35 $n92 1.5Mb 950ms DropTail
$ns duplex-link-of-interfaces $n35 $n87 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n35 $n83 1.5Mb 150ms DropTail
$ns duplex-link-of-interfaces $n35 $n79 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n35 $n77 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n35 $n75 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n35 $n73 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n35 $n66 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n35 $n60 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n35 $n58 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n35 $n57 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n35 $n55 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n35 $n51 1.5Mb 890ms DropTail
$ns duplex-link-of-interfaces $n35 $n50 1.5Mb 810ms DropTail
$ns duplex-link-of-interfaces $n35 $n49 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n35 $n45 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n36 $n90 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n36 $n78 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n36 $n64 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n36 $n63 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n36 $n59 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n36 $n57 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n36 $n54 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n36 $n52 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n36 $n48 1.5Mb 140ms DropTail
$ns duplex-link-of-interfaces $n36 $n39 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n37 $n88 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n37 $n79 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n37 $n77 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n37 $n73 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n37 $n70 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n37 $n68 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n37 $n67 1.5Mb 750ms DropTail
$ns duplex-link-of-interfaces $n37 $n66 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n37 $n64 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n37 $n63 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n37 $n56 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n37 $n54 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n37 $n49 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n37 $n41 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n37 $n39 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n38 $n90 1.5Mb 650ms DropTail
$ns duplex-link-of-interfaces $n38 $n84 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n38 $n83 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n38 $n82 1.5Mb 150ms DropTail
$ns duplex-link-of-interfaces $n38 $n80 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n38 $n78 1.5Mb 130ms DropTail
$ns duplex-link-of-interfaces $n38 $n75 1.5Mb 50ms DropTail
$ns duplex-link-of-interfaces $n38 $n68 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n38 $n66 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n38 $n54 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n38 $n49 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n38 $n42 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n39 $n97 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n39 $n91 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n39 $n90 1.5Mb 100ms DropTail
$ns duplex-link-of-interfaces $n39 $n89 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n39 $n81 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n39 $n71 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n39 $n63 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n39 $n56 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n39 $n55 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n40 $n85 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n40 $n73 1.5Mb 140ms DropTail
$ns duplex-link-of-interfaces $n40 $n65 1.5Mb 120ms DropTail
$ns duplex-link-of-interfaces $n40 $n60 1.5Mb 40ms DropTail
$ns duplex-link-of-interfaces $n40 $n58 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n40 $n57 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n40 $n42 1.5Mb 810ms DropTail
$ns duplex-link-of-interfaces $n41 $n98 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n41 $n91 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n41 $n88 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n41 $n86 1.5Mb 10ms DropTail
$ns duplex-link-of-interfaces $n41 $n83 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n41 $n78 1.5Mb 190ms DropTail
$ns duplex-link-of-interfaces $n41 $n61 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n41 $n60 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n41 $n55 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n41 $n53 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n41 $n49 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n41 $n43 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n42 $n99 1.5Mb 980ms DropTail
$ns duplex-link-of-interfaces $n42 $n85 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n42 $n84 1.5Mb 120ms DropTail
$ns duplex-link-of-interfaces $n42 $n80 1.5Mb 740ms DropTail
$ns duplex-link-of-interfaces $n42 $n64 1.5Mb 950ms DropTail
$ns duplex-link-of-interfaces $n42 $n63 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n42 $n59 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n42 $n57 1.5Mb 970ms DropTail
$ns duplex-link-of-interfaces $n42 $n56 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n43 $n91 1.5Mb 60ms DropTail
$ns duplex-link-of-interfaces $n43 $n87 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n43 $n86 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n43 $n84 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n43 $n82 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n43 $n70 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n43 $n66 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n43 $n65 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n43 $n51 1.5Mb 840ms DropTail
$ns duplex-link-of-interfaces $n43 $n50 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n43 $n45 1.5Mb 710ms DropTail
$ns duplex-link-of-interfaces $n44 $n95 1.5Mb 50ms DropTail
$ns duplex-link-of-interfaces $n44 $n88 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n44 $n80 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n44 $n79 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n44 $n77 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n44 $n76 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n44 $n68 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n44 $n67 1.5Mb 90ms DropTail
$ns duplex-link-of-interfaces $n44 $n61 1.5Mb 140ms DropTail
$ns duplex-link-of-interfaces $n44 $n58 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n44 $n55 1.5Mb 70ms DropTail
$ns duplex-link-of-interfaces $n44 $n53 1.5Mb 870ms DropTail
$ns duplex-link-of-interfaces $n44 $n49 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n45 $n97 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n45 $n92 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n45 $n86 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n45 $n84 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n45 $n77 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n45 $n76 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n45 $n70 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n45 $n59 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n45 $n57 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n45 $n52 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n46 $n82 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n46 $n79 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n46 $n64 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n46 $n61 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n46 $n59 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n46 $n53 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n47 $n83 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n47 $n82 1.5Mb 880ms DropTail
$ns duplex-link-of-interfaces $n47 $n67 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n47 $n61 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n47 $n56 1.5Mb 610ms DropTail
$ns duplex-link-of-interfaces $n47 $n55 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n47 $n54 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n47 $n52 1.5Mb 730ms DropTail
$ns duplex-link-of-interfaces $n47 $n50 1.5Mb 60ms DropTail
$ns duplex-link-of-interfaces $n47 $n48 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n48 $n91 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n48 $n77 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n48 $n72 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n48 $n57 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n48 $n55 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n49 $n92 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n49 $n89 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n49 $n84 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n49 $n80 1.5Mb 60ms DropTail
$ns duplex-link-of-interfaces $n49 $n79 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n49 $n78 1.5Mb 820ms DropTail
$ns duplex-link-of-interfaces $n49 $n76 1.5Mb 700ms DropTail
$ns duplex-link-of-interfaces $n49 $n72 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n49 $n71 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n49 $n70 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n50 $n92 1.5Mb 140ms DropTail
$ns duplex-link-of-interfaces $n50 $n89 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n50 $n83 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n50 $n78 1.5Mb 910ms DropTail
$ns duplex-link-of-interfaces $n50 $n76 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n50 $n73 1.5Mb 590ms DropTail
$ns duplex-link-of-interfaces $n50 $n51 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n51 $n99 1.5Mb 960ms DropTail
$ns duplex-link-of-interfaces $n51 $n88 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n51 $n75 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n51 $n69 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n51 $n64 1.5Mb 780ms DropTail
$ns duplex-link-of-interfaces $n51 $n60 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n51 $n59 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n51 $n55 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n52 $n96 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n52 $n89 1.5Mb 730ms DropTail
$ns duplex-link-of-interfaces $n52 $n85 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n52 $n78 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n52 $n76 1.5Mb 70ms DropTail
$ns duplex-link-of-interfaces $n52 $n72 1.5Mb 120ms DropTail
$ns duplex-link-of-interfaces $n52 $n66 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n52 $n58 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n52 $n57 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n52 $n54 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n53 $n98 1.5Mb 880ms DropTail
$ns duplex-link-of-interfaces $n53 $n85 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n53 $n78 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n53 $n65 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n53 $n61 1.5Mb 890ms DropTail
$ns duplex-link-of-interfaces $n53 $n57 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n54 $n96 1.5Mb 150ms DropTail
$ns duplex-link-of-interfaces $n54 $n95 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n54 $n77 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n54 $n76 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n54 $n69 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n54 $n68 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n54 $n67 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n54 $n65 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n54 $n62 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n54 $n59 1.5Mb 210ms DropTail
$ns duplex-link-of-interfaces $n54 $n58 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n54 $n57 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n55 $n98 1.5Mb 140ms DropTail
$ns duplex-link-of-interfaces $n55 $n93 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n55 $n74 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n55 $n63 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n55 $n60 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n56 $n89 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n56 $n85 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n56 $n84 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n56 $n80 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n56 $n75 1.5Mb 170ms DropTail
$ns duplex-link-of-interfaces $n56 $n66 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n56 $n64 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n57 $n95 1.5Mb 710ms DropTail
$ns duplex-link-of-interfaces $n57 $n86 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n57 $n78 1.5Mb 520ms DropTail
$ns duplex-link-of-interfaces $n57 $n76 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n57 $n69 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n57 $n65 1.5Mb 130ms DropTail
$ns duplex-link-of-interfaces $n57 $n64 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n58 $n97 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n58 $n94 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n58 $n91 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n58 $n89 1.5Mb 850ms DropTail
$ns duplex-link-of-interfaces $n58 $n83 1.5Mb 710ms DropTail
$ns duplex-link-of-interfaces $n58 $n82 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n58 $n80 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n58 $n75 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n58 $n60 1.5Mb 680ms DropTail
$ns duplex-link-of-interfaces $n59 $n97 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n59 $n95 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n59 $n88 1.5Mb 150ms DropTail
$ns duplex-link-of-interfaces $n59 $n75 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n59 $n74 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n59 $n69 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n59 $n67 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n59 $n62 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n60 $n98 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n60 $n95 1.5Mb 540ms DropTail
$ns duplex-link-of-interfaces $n60 $n91 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n60 $n90 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n60 $n89 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n60 $n85 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n60 $n82 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n60 $n80 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n60 $n77 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n60 $n76 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n60 $n74 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n61 $n87 1.5Mb 60ms DropTail
$ns duplex-link-of-interfaces $n61 $n77 1.5Mb 100ms DropTail
$ns duplex-link-of-interfaces $n61 $n73 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n61 $n69 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n62 $n92 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n62 $n82 1.5Mb 670ms DropTail
$ns duplex-link-of-interfaces $n62 $n69 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n63 $n98 1.5Mb 740ms DropTail
$ns duplex-link-of-interfaces $n63 $n96 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n63 $n89 1.5Mb 820ms DropTail
$ns duplex-link-of-interfaces $n63 $n78 1.5Mb 50ms DropTail
$ns duplex-link-of-interfaces $n63 $n71 1.5Mb 300ms DropTail
$ns duplex-link-of-interfaces $n63 $n67 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n64 $n95 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n64 $n91 1.5Mb 560ms DropTail
$ns duplex-link-of-interfaces $n64 $n81 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n64 $n74 1.5Mb 620ms DropTail
$ns duplex-link-of-interfaces $n64 $n71 1.5Mb 580ms DropTail
$ns duplex-link-of-interfaces $n64 $n68 1.5Mb 840ms DropTail
$ns duplex-link-of-interfaces $n64 $n65 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n65 $n98 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n65 $n87 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n65 $n85 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n65 $n84 1.5Mb 740ms DropTail
$ns duplex-link-of-interfaces $n65 $n79 1.5Mb 210ms DropTail
$ns duplex-link-of-interfaces $n65 $n78 1.5Mb 490ms DropTail
$ns duplex-link-of-interfaces $n65 $n73 1.5Mb 70ms DropTail
$ns duplex-link-of-interfaces $n66 $n90 1.5Mb 220ms DropTail
$ns duplex-link-of-interfaces $n66 $n87 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n66 $n85 1.5Mb 110ms DropTail
$ns duplex-link-of-interfaces $n66 $n81 1.5Mb 10ms DropTail
$ns duplex-link-of-interfaces $n66 $n67 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n67 $n97 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n67 $n95 1.5Mb 130ms DropTail
$ns duplex-link-of-interfaces $n67 $n86 1.5Mb 570ms DropTail
$ns duplex-link-of-interfaces $n67 $n80 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n67 $n78 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n67 $n73 1.5Mb 650ms DropTail
$ns duplex-link-of-interfaces $n67 $n72 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n68 $n99 1.5Mb 690ms DropTail
$ns duplex-link-of-interfaces $n68 $n91 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n68 $n87 1.5Mb 180ms DropTail
$ns duplex-link-of-interfaces $n68 $n86 1.5Mb 230ms DropTail
$ns duplex-link-of-interfaces $n68 $n85 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n68 $n75 1.5Mb 380ms DropTail
$ns duplex-link-of-interfaces $n69 $n97 1.5Mb 70ms DropTail
$ns duplex-link-of-interfaces $n69 $n96 1.5Mb 140ms DropTail
$ns duplex-link-of-interfaces $n69 $n95 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n69 $n83 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n69 $n76 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n69 $n73 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n69 $n72 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n70 $n93 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n70 $n92 1.5Mb 850ms DropTail
$ns duplex-link-of-interfaces $n70 $n85 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n70 $n84 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n70 $n83 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n70 $n82 1.5Mb 400ms DropTail
$ns duplex-link-of-interfaces $n70 $n77 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n71 $n99 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n71 $n97 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n71 $n94 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n71 $n87 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n71 $n86 1.5Mb 340ms DropTail
$ns duplex-link-of-interfaces $n71 $n85 1.5Mb 320ms DropTail
$ns duplex-link-of-interfaces $n72 $n85 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n72 $n81 1.5Mb 280ms DropTail
$ns duplex-link-of-interfaces $n73 $n93 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n73 $n92 1.5Mb 720ms DropTail
$ns duplex-link-of-interfaces $n73 $n89 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n73 $n83 1.5Mb 130ms DropTail
$ns duplex-link-of-interfaces $n73 $n81 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n73 $n76 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n74 $n98 1.5Mb 100ms DropTail
$ns duplex-link-of-interfaces $n74 $n96 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n74 $n94 1.5Mb 380ms DropTail
$ns duplex-link-of-interfaces $n74 $n90 1.5Mb 380ms DropTail
$ns duplex-link-of-interfaces $n74 $n84 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n74 $n83 1.5Mb 830ms DropTail
$ns duplex-link-of-interfaces $n74 $n81 1.5Mb 370ms DropTail
$ns duplex-link-of-interfaces $n75 $n92 1.5Mb 910ms DropTail
$ns duplex-link-of-interfaces $n75 $n91 1.5Mb 240ms DropTail
$ns duplex-link-of-interfaces $n75 $n90 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n75 $n82 1.5Mb 120ms DropTail
$ns duplex-link-of-interfaces $n75 $n80 1.5Mb 630ms DropTail
$ns duplex-link-of-interfaces $n76 $n94 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n76 $n83 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n76 $n82 1.5Mb 190ms DropTail
$ns duplex-link-of-interfaces $n76 $n77 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n77 $n88 1.5Mb 430ms DropTail
$ns duplex-link-of-interfaces $n77 $n81 1.5Mb 360ms DropTail
$ns duplex-link-of-interfaces $n77 $n80 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n78 $n94 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n78 $n83 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n79 $n97 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n79 $n96 1.5Mb 160ms DropTail
$ns duplex-link-of-interfaces $n79 $n91 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n79 $n88 1.5Mb 80ms DropTail
$ns duplex-link-of-interfaces $n79 $n85 1.5Mb 270ms DropTail
$ns duplex-link-of-interfaces $n80 $n95 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n80 $n87 1.5Mb 500ms DropTail
$ns duplex-link-of-interfaces $n80 $n82 1.5Mb 730ms DropTail
$ns duplex-link-of-interfaces $n81 $n97 1.5Mb 190ms DropTail
$ns duplex-link-of-interfaces $n81 $n94 1.5Mb 40ms DropTail
$ns duplex-link-of-interfaces $n81 $n84 1.5Mb 440ms DropTail
$ns duplex-link-of-interfaces $n81 $n83 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n82 $n92 1.5Mb 1020ms DropTail
$ns duplex-link-of-interfaces $n82 $n85 1.5Mb 610ms DropTail
$ns duplex-link-of-interfaces $n83 $n98 1.5Mb 730ms DropTail
$ns duplex-link-of-interfaces $n83 $n96 1.5Mb 460ms DropTail
$ns duplex-link-of-interfaces $n83 $n95 1.5Mb 650ms DropTail
$ns duplex-link-of-interfaces $n83 $n84 1.5Mb 760ms DropTail
$ns duplex-link-of-interfaces $n84 $n95 1.5Mb 260ms DropTail
$ns duplex-link-of-interfaces $n84 $n89 1.5Mb 910ms DropTail
$ns duplex-link-of-interfaces $n85 $n98 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n85 $n97 1.5Mb 190ms DropTail
$ns duplex-link-of-interfaces $n85 $n92 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n86 $n99 1.5Mb 600ms DropTail
$ns duplex-link-of-interfaces $n86 $n97 1.5Mb 330ms DropTail
$ns duplex-link-of-interfaces $n86 $n95 1.5Mb 530ms DropTail
$ns duplex-link-of-interfaces $n86 $n94 1.5Mb 550ms DropTail
$ns duplex-link-of-interfaces $n86 $n87 1.5Mb 390ms DropTail
$ns duplex-link-of-interfaces $n88 $n99 1.5Mb 450ms DropTail
$ns duplex-link-of-interfaces $n88 $n96 1.5Mb 80ms DropTail
$ns duplex-link-of-interfaces $n89 $n98 1.5Mb 660ms DropTail
$ns duplex-link-of-interfaces $n89 $n93 1.5Mb 920ms DropTail
$ns duplex-link-of-interfaces $n90 $n98 1.5Mb 310ms DropTail
$ns duplex-link-of-interfaces $n90 $n97 1.5Mb 410ms DropTail
$ns duplex-link-of-interfaces $n90 $n96 1.5Mb 200ms DropTail
$ns duplex-link-of-interfaces $n90 $n92 1.5Mb 290ms DropTail
$ns duplex-link-of-interfaces $n90 $n91 1.5Mb 510ms DropTail
$ns duplex-link-of-interfaces $n91 $n94 1.5Mb 380ms DropTail
$ns duplex-link-of-interfaces $n92 $n98 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n92 $n97 1.5Mb 640ms DropTail
$ns duplex-link-of-interfaces $n92 $n95 1.5Mb 480ms DropTail
$ns duplex-link-of-interfaces $n93 $n98 1.5Mb 420ms DropTail
$ns duplex-link-of-interfaces $n93 $n97 1.5Mb 350ms DropTail
$ns duplex-link-of-interfaces $n93 $n96 1.5Mb 470ms DropTail
$ns duplex-link-of-interfaces $n94 $n96 1.5Mb 20ms DropTail
$ns duplex-link-of-interfaces $n94 $n95 1.5Mb 250ms DropTail
$ns duplex-link-of-interfaces $n97 $n99 1.5Mb 490ms DropTail

set ctrmcastcomp [new CtrMcastComp $ns]
set ctrrpcomp [new CtrRPComp $ns]

set ctrmcast0 [new CtrMcast $ns $n0 $ctrmcastcomp [list 1 1]]
set ctrmcast1 [new CtrMcast $ns $n1 $ctrmcastcomp [list 1 1]]
set ctrmcast2 [new CtrMcast $ns $n2 $ctrmcastcomp [list 1 1]]
set ctrmcast3 [new CtrMcast $ns $n3 $ctrmcastcomp [list 1 1]]
set ctrmcast4 [new CtrMcast $ns $n4 $ctrmcastcomp [list 1 1]]
set ctrmcast5 [new CtrMcast $ns $n5 $ctrmcastcomp [list 1 1]]
set ctrmcast6 [new CtrMcast $ns $n6 $ctrmcastcomp [list 1 1]]
set ctrmcast7 [new CtrMcast $ns $n7 $ctrmcastcomp [list 1 1]]
set ctrmcast8 [new CtrMcast $ns $n8 $ctrmcastcomp [list 1 1]]
set ctrmcast9 [new CtrMcast $ns $n9 $ctrmcastcomp [list 1 1]]
set ctrmcast10 [new CtrMcast $ns $n10 $ctrmcastcomp [list 1 1]]
set ctrmcast11 [new CtrMcast $ns $n11 $ctrmcastcomp [list 1 1]]
set ctrmcast12 [new CtrMcast $ns $n12 $ctrmcastcomp [list 1 1]]
set ctrmcast13 [new CtrMcast $ns $n13 $ctrmcastcomp [list 1 1]]
set ctrmcast14 [new CtrMcast $ns $n14 $ctrmcastcomp [list 1 1]]
set ctrmcast15 [new CtrMcast $ns $n15 $ctrmcastcomp [list 1 1]]
set ctrmcast16 [new CtrMcast $ns $n16 $ctrmcastcomp [list 1 1]]
set ctrmcast17 [new CtrMcast $ns $n17 $ctrmcastcomp [list 1 1]]
set ctrmcast18 [new CtrMcast $ns $n18 $ctrmcastcomp [list 1 1]]
set ctrmcast19 [new CtrMcast $ns $n19 $ctrmcastcomp [list 1 1]]
set ctrmcast20 [new CtrMcast $ns $n20 $ctrmcastcomp [list 1 1]]
set ctrmcast21 [new CtrMcast $ns $n21 $ctrmcastcomp [list 1 1]]
set ctrmcast22 [new CtrMcast $ns $n22 $ctrmcastcomp [list 1 1]]
set ctrmcast23 [new CtrMcast $ns $n23 $ctrmcastcomp [list 1 1]]
set ctrmcast24 [new CtrMcast $ns $n24 $ctrmcastcomp [list 1 1]]
set ctrmcast25 [new CtrMcast $ns $n25 $ctrmcastcomp [list 1 1]]
set ctrmcast26 [new CtrMcast $ns $n26 $ctrmcastcomp [list 1 1]]
set ctrmcast27 [new CtrMcast $ns $n27 $ctrmcastcomp [list 1 1]]
set ctrmcast28 [new CtrMcast $ns $n28 $ctrmcastcomp [list 1 1]]
set ctrmcast29 [new CtrMcast $ns $n29 $ctrmcastcomp [list 1 1]]
set ctrmcast30 [new CtrMcast $ns $n30 $ctrmcastcomp [list 1 1]]
set ctrmcast31 [new CtrMcast $ns $n31 $ctrmcastcomp [list 1 1]]
set ctrmcast32 [new CtrMcast $ns $n32 $ctrmcastcomp [list 1 1]]
set ctrmcast33 [new CtrMcast $ns $n33 $ctrmcastcomp [list 1 1]]
set ctrmcast34 [new CtrMcast $ns $n34 $ctrmcastcomp [list 1 1]]
set ctrmcast35 [new CtrMcast $ns $n35 $ctrmcastcomp [list 1 1]]
set ctrmcast36 [new CtrMcast $ns $n36 $ctrmcastcomp [list 1 1]]
set ctrmcast37 [new CtrMcast $ns $n37 $ctrmcastcomp [list 1 1]]
set ctrmcast38 [new CtrMcast $ns $n38 $ctrmcastcomp [list 1 1]]
set ctrmcast39 [new CtrMcast $ns $n39 $ctrmcastcomp [list 1 1]]
set ctrmcast40 [new CtrMcast $ns $n40 $ctrmcastcomp [list 1 1]]
set ctrmcast41 [new CtrMcast $ns $n41 $ctrmcastcomp [list 1 1]]
set ctrmcast42 [new CtrMcast $ns $n42 $ctrmcastcomp [list 1 1]]
set ctrmcast43 [new CtrMcast $ns $n43 $ctrmcastcomp [list 1 1]]
set ctrmcast44 [new CtrMcast $ns $n44 $ctrmcastcomp [list 1 1]]
set ctrmcast45 [new CtrMcast $ns $n45 $ctrmcastcomp [list 1 1]]
set ctrmcast46 [new CtrMcast $ns $n46 $ctrmcastcomp [list 1 1]]
set ctrmcast47 [new CtrMcast $ns $n47 $ctrmcastcomp [list 1 1]]
set ctrmcast48 [new CtrMcast $ns $n48 $ctrmcastcomp [list 1 1]]
set ctrmcast49 [new CtrMcast $ns $n49 $ctrmcastcomp [list 1 1]]
set ctrmcast50 [new CtrMcast $ns $n50 $ctrmcastcomp [list 1 1]]
set ctrmcast51 [new CtrMcast $ns $n51 $ctrmcastcomp [list 1 1]]
set ctrmcast52 [new CtrMcast $ns $n52 $ctrmcastcomp [list 1 1]]
set ctrmcast53 [new CtrMcast $ns $n53 $ctrmcastcomp [list 1 1]]
set ctrmcast54 [new CtrMcast $ns $n54 $ctrmcastcomp [list 1 1]]
set ctrmcast55 [new CtrMcast $ns $n55 $ctrmcastcomp [list 1 1]]
set ctrmcast56 [new CtrMcast $ns $n56 $ctrmcastcomp [list 1 1]]
set ctrmcast57 [new CtrMcast $ns $n57 $ctrmcastcomp [list 1 1]]
set ctrmcast58 [new CtrMcast $ns $n58 $ctrmcastcomp [list 1 1]]
set ctrmcast59 [new CtrMcast $ns $n59 $ctrmcastcomp [list 1 1]]
set ctrmcast60 [new CtrMcast $ns $n60 $ctrmcastcomp [list 1 1]]
set ctrmcast61 [new CtrMcast $ns $n61 $ctrmcastcomp [list 1 1]]
set ctrmcast62 [new CtrMcast $ns $n62 $ctrmcastcomp [list 1 1]]
set ctrmcast63 [new CtrMcast $ns $n63 $ctrmcastcomp [list 1 1]]
set ctrmcast64 [new CtrMcast $ns $n64 $ctrmcastcomp [list 1 1]]
set ctrmcast65 [new CtrMcast $ns $n65 $ctrmcastcomp [list 1 1]]
set ctrmcast66 [new CtrMcast $ns $n66 $ctrmcastcomp [list 1 1]]
set ctrmcast67 [new CtrMcast $ns $n67 $ctrmcastcomp [list 1 1]]
set ctrmcast68 [new CtrMcast $ns $n68 $ctrmcastcomp [list 1 1]]
set ctrmcast69 [new CtrMcast $ns $n69 $ctrmcastcomp [list 1 1]]
set ctrmcast70 [new CtrMcast $ns $n70 $ctrmcastcomp [list 1 1]]
set ctrmcast71 [new CtrMcast $ns $n71 $ctrmcastcomp [list 1 1]]
set ctrmcast72 [new CtrMcast $ns $n72 $ctrmcastcomp [list 1 1]]
set ctrmcast73 [new CtrMcast $ns $n73 $ctrmcastcomp [list 1 1]]
set ctrmcast74 [new CtrMcast $ns $n74 $ctrmcastcomp [list 1 1]]
set ctrmcast75 [new CtrMcast $ns $n75 $ctrmcastcomp [list 1 1]]
set ctrmcast76 [new CtrMcast $ns $n76 $ctrmcastcomp [list 1 1]]
set ctrmcast77 [new CtrMcast $ns $n77 $ctrmcastcomp [list 1 1]]
set ctrmcast78 [new CtrMcast $ns $n78 $ctrmcastcomp [list 1 1]]
set ctrmcast79 [new CtrMcast $ns $n79 $ctrmcastcomp [list 1 1]]
set ctrmcast80 [new CtrMcast $ns $n80 $ctrmcastcomp [list 1 1]]
set ctrmcast81 [new CtrMcast $ns $n81 $ctrmcastcomp [list 1 1]]
set ctrmcast82 [new CtrMcast $ns $n82 $ctrmcastcomp [list 1 1]]
set ctrmcast83 [new CtrMcast $ns $n83 $ctrmcastcomp [list 1 1]]
set ctrmcast84 [new CtrMcast $ns $n84 $ctrmcastcomp [list 1 1]]
set ctrmcast85 [new CtrMcast $ns $n85 $ctrmcastcomp [list 1 1]]
set ctrmcast86 [new CtrMcast $ns $n86 $ctrmcastcomp [list 1 1]]
set ctrmcast87 [new CtrMcast $ns $n87 $ctrmcastcomp [list 1 1]]
set ctrmcast88 [new CtrMcast $ns $n88 $ctrmcastcomp [list 1 1]]
set ctrmcast89 [new CtrMcast $ns $n89 $ctrmcastcomp [list 1 1]]
set ctrmcast90 [new CtrMcast $ns $n90 $ctrmcastcomp [list 1 1]]
set ctrmcast91 [new CtrMcast $ns $n91 $ctrmcastcomp [list 1 1]]
set ctrmcast92 [new CtrMcast $ns $n92 $ctrmcastcomp [list 1 1]]
set ctrmcast93 [new CtrMcast $ns $n93 $ctrmcastcomp [list 1 1]]
set ctrmcast94 [new CtrMcast $ns $n94 $ctrmcastcomp [list 1 1]]
set ctrmcast95 [new CtrMcast $ns $n95 $ctrmcastcomp [list 1 1]]
set ctrmcast96 [new CtrMcast $ns $n96 $ctrmcastcomp [list 1 1]]
set ctrmcast97 [new CtrMcast $ns $n97 $ctrmcastcomp [list 1 1]]
set ctrmcast98 [new CtrMcast $ns $n98 $ctrmcastcomp [list 1 1]]
set ctrmcast99 [new CtrMcast $ns $n99 $ctrmcastcomp [list 1 1]]

$ns compute-routes
$ctrrpcomp compute-rpset

set rcvr18 [new Agent/Null]
$ns attach-agent $n18 $rcvr18
$ns at 19 "$n18 join-group $rcvr18 0x8003"
set rcvr87 [new Agent/Null]
$ns attach-agent $n87 $rcvr87
$ns at 88 "$n87 join-group $rcvr87 0x8003"
set rcvr91 [new Agent/Null]
$ns attach-agent $n91 $rcvr91
$ns at 92 "$n91 join-group $rcvr91 0x8003"
set rcvr23 [new Agent/Null]
$ns attach-agent $n23 $rcvr23
$ns at 24 "$n23 join-group $rcvr23 0x8003"
set rcvr17 [new Agent/Null]
$ns attach-agent $n17 $rcvr17
$ns at 18 "$n17 join-group $rcvr17 0x8003"
set rcvr65 [new Agent/Null]
$ns attach-agent $n65 $rcvr65
$ns at 66 "$n65 join-group $rcvr65 0x8003"
set rcvr14 [new Agent/Null]
$ns attach-agent $n14 $rcvr14
$ns at 15 "$n14 join-group $rcvr14 0x8003"
set rcvr97 [new Agent/Null]
$ns attach-agent $n97 $rcvr97
$ns at 98 "$n97 join-group $rcvr97 0x8003"
set rcvr19 [new Agent/Null]
$ns attach-agent $n19 $rcvr19
$ns at 20 "$n19 join-group $rcvr19 0x8003"
set rcvr66 [new Agent/Null]
$ns attach-agent $n66 $rcvr66
$ns at 67 "$n66 join-group $rcvr66 0x8003"

set sender [new Agent/CBR]
$sender set dst_ 0x8003
$sender set class_ 2
$ns attach-agent $n2 $sender

$ns at 0 "$sender start"

# START ns
$ns at 11 "exit 0"
$ns run

