#! /bin/sh
# script to run all tests in test-suite.tcl
#
# Copyright (c) 1995 The Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
#	This product includes software developed by the Network Research
#	Group at Lawrence Berkeley National Laboratory.
# 4. Neither the name of the University nor of the Laboratory may be used
#    to endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# @(#) $Header: /home/smtatapudi/Thesis/nsnam/nsnam/ns-2/test-all,v 1.6 1997/07/26 05:56:00 sfloyd Exp $
#
# This script was written and contributed by Matt Mathis (mathis@psc.edu)
#
tests=`awk '/^Class Test\//{ print substr($2,index($2, "/")+1) }' \
  test-suite.tcl`

# Note that the telnet test includes random source behavior - its output
# is not currently repeatable from run to run

if [ ! -d test-output ]; then
	mkdir test-output
fi

echo $tests
for t in $tests; do
    echo
    echo Running test $t

    # Beware that xgraph is run on temp.rands asynchronously, if it
    # is slow to launch, you may get an incorrect graph
    ./ns test-suite.tcl $t
    if [ -f temp.rands ]; then
	if [ ! -f test-output/$t ]; then
	    echo saving output for future validation
	    cp temp.rands test-output/$t
	else
	    cmp -s temp.rands test-output/$t
	    if [ $? = 0 ]; then
		echo Test output agrees with reference output
	    else
		echo Test output differs from reference output
		cp temp.rands test-output/$t.test
		echo "Diagnose with: diff test-output/$t.test test-output/$t"
		echo "Differences due to floating-point formatting are not significant."
		echo "Tests telnet, reno4, reno4a, and phase2 all use randomization,"
		echo "and can give different results for different random number generators."
	    fi
	fi
    fi
    echo 'next?'
    read answer
done
