#!/bin/sh
##
## As a temporary measure, one of the ways to run automatic validation
## is the following:
## ./validate > out ; diff out validate.out
##
## If all that prints out is a list of messages about
## "warning: using backward compatibility mode",
## then the automatic validation scripts ran correctly.
##

echo "*** test-all"
./test-all quiet

cd tcl/test
for i in red sack schedule tcp red-v1 cbq-v1 sack-v1 v1
do
	p=./test-all-$i
	echo "*** $p"
	$p quiet
done

exit 0
