#! /bin/sh
echo "parsing tcpdump file"
date
./tcpdump -n -tt -r $1 tcp src port 80 > $1.http-srv

echo "run http_connect"
date
sort -s -o $1.http-srv-sort +1 -2 +3 -4 +0 -1 -T /tmp $1.http-srv
http_connect -r $1.http-srv -w $1.http-srv.connect

grep "ACT" $1.http-srv.connect > $1.http-srv.connect.time
sort $1.http-srv.connect.time > $1.http-srv.connect.time.sort

echo "run http_active"
date
sort -s -o $1.http-srv.connect.sort +1 -2 +0 -1 -T /tmp $1.http-srv.connect
http_active -r $1.http-srv.connect.sort -w $1.http-srv.active -I $2

echo "compute CDF statistics"
date
outputCDF $1.http-srv.active.activity
echo "compute time series (1ms block)"
date
bw.tcl $1.http-srv
cat $1.http-srv.bw | time-series.pl > $1.time-series
echo "execution complete"
date
