#! /bin/sh
#
# Copyright (c) Xerox Corporation 1998. All rights reserved.
#
# License is granted to copy, to use, and to make and to use derivative
# works for research and evaluation purposes, provided that Xerox is
# acknowledged in all documentation pertaining to any such copy or
# derivative work. Xerox grants no other licenses expressed or
# implied. The Xerox trade name should not be used in any advertising
# without its written permission. 
#
# XEROX CORPORATION MAKES NO REPRESENTATIONS CONCERNING EITHER THE
# MERCHANTABILITY OF THIS SOFTWARE OR THE SUITABILITY OF THIS SOFTWARE
# FOR ANY PARTICULAR PURPOSE.  The software is provided "as is" without
# express or implied warranty of any kind.
#
# These notices must be retained in any copies of any part of this
# software. 
#
# Test suite for web caching code. Based on test-all-full by Kevin.
#
# $Header: /home/smtatapudi/Thesis/nsnam/nsnam/ns-2/tcl/test/test-all-mcache,v 1.1 1999/07/02 21:16:42 haoboy Exp $

file="test-suite-mcache.tcl"
directory="test-output-mcache"
version="v2"
if [ $# -ge 1 ]
then
	flag=$1
	./test-all-template1 $file $directory $version $flag
else
	./test-all-template1 $file $directory $version
fi
