#! /bin/sh

#
# Copyright (c) 1997 University of Southern California.
# All rights reserved.                                            
#                                                                
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation, advertising
# materials, and other materials related to such distribution and use
# acknowledge that the software was developed by the University of
# Southern California, Information Sciences Institute.  The name of the
# University may not be used to endorse or promote products derived from
# this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#
# This file is taken directly from test-vegas in ns v1,
# contributed by Ted Kuo <tkuo@eos.ncsu.edu>.
#

#holes=2		* from NSA in packet.h
NS=../../ns
rm -f t0
cp test-suite-vegas-v1.tcl t0
sed -e 's/maxBurst/0/' t0 > t		# for tahoe, reno, vegas
sed -e 's/maxBurst/4/' t0 > t1		# for newreno, sack, fack
sed -e 's/connection tcp /connection tcp-reno /' -e s/type/reno/ t > t1.tcl
sed -e 's/connection tcp /connection tcp-sack1 /' t1 > t2
sed -e 's/tcp-sink/sack1-tcp-sink/' -e 's/type/sck1/' t2 > t4.tcl

# vegas
sed -e 's/connection tcp /connection tcp-vegas /' -e s/type/vegas/ t > t8.tcl


tests=`awk '/^proc test_/{ print substr($2,index($2, "_")+1) }' vegas.tcl`

for t in $tests; do
    echo
    echo Running test $t
    echo 'Reno:'
    $NS t1.tcl $t
    sleep 5
    echo 'Sack1:'
    $NS t4.tcl $t
    sleep 5
    echo 'Vegas:'
    $NS t8.tcl $t
    echo 'next?'
    read answer
done
