#! /bin/sh
#holes=2		* from NSA in packet.h
sed -e 's/maxBurst/0/' sack.tcl > t		# for tahoe, reno
sed -e 's/maxBurst/4/' sack.tcl > t1		# for newreno, sack
sed -e 's/type/taho/' t > t0.tcl
sed -e 's/connection tcp/connection tcp-reno/' -e s/type/reno/ t > t1.tcl
sed -e 's/connection tcp/connection tcp-newreno/' -e s/type/newr/ t1 > t3.tcl
sed -e 's/connection tcp/connection tcp-sack1/' t1 > t2
sed -e 's/tcp-sink/sack1-tcp-sink/' -e 's/type/sck1/' t2 > t4.tcl


tests=`awk '/^proc test_/{ print substr($2,index($2, "_")+1) }' sack.tcl`

for t in $tests; do
    echo
    echo Running test $t
    echo 'Tahoe:'
    ns t0.tcl $t
    sleep 5
    echo 'Reno:'
    ns t1.tcl $t
    sleep 5
    echo 'New Reno without Sack:'
    ns t3.tcl $t
    sleep 5
    echo 'Sack1:'
    ns t4.tcl $t
    echo 'next?'
    read answer
done

# ns t0.tcl one_40
