#! /bin/sh
#
# Copyright (C) 2000 by USC/ISI
# All rights reserved.
#
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation, advertising
# materials, and other materials related to such distribution and use
# acknowledge that the software was developed by the University of
# Southern California, Information Sciences Institute.  The name of the
# University may not be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#

#
#
#

die() {
	echo "$@"  1>&2
	test ! -z "$blame" && echo "$blame" 1>&2
	exit 1
}

warn() {
	echo "$@"
}

# Get current path
CUR_PATH=`pwd`

# create tcl8.3.2 and tk8.3.2 installation directory

if [ ! -d tclbox ]
then
	mkdir tclbox
else
	rm -fr tclbox
fi

if [ ! -d tkbox ]
then
	mkdir tkbox
else
	rm -fr tkbox
fi

# install and install Tcl8.3.2

cd ./tcl8.3.2/unix
if [ -f Makefile ] ; then 
	make distclean
fi

blame='Tcl is not part of the ns project.  Please see www.Scriptics.com
to see if they have a fix for your platform.'
./configure --enable-gcc --prefix="$CUR_PATH/tclbox" || die "tcl8.3.2 configuration failed! Exiting ..."
if make 
then 
	make install || die "tcl8.3.2 installation failed! Exiting ..."
else
	echo "tcl8.3.2 make failed! Exiting ..."
	echo "For problems with Tcl/Tk see http://www.scriptics.com"
	exit
fi

cd ../../

# compile and install tk

cd ./tk8.3.2/unix
if [ -f Makefile ] ; then
	make distclean
fi

blame='Tk is not part of the ns project.  Please see www.Scriptics.com
to see if they have a fix for your platform.'
./configure --enable-gcc --prefix="$CUR_PATH/tkbox" || die "tk8.3.2 configuration failed! Exiting ..."
if make 
then
	make install || die "tk8.3.2 installation failed! Exiting ..."
else
	echo "tk8.3.2 make failed! Exiting ..."
	echo "For problems with Tcl/Tk see http://www.scriptics.com"
	exit
fi


cd ../../

# do some copy for otcl

cp ./tcl8.3.2/generic/*.h ./tclbox/include/ || die "cp failed"
cp ./tk8.3.2/generic/*.h ./tkbox/include/ || die "cp failed"

# compile and install otcl

cd ./otcl-1.0a6

blame='Please check http://www.isi.edu/nsnam/ns/ns-problems.html
for common problems and bug fixes.'
./configure --with-tcl=../tclbox --with-tk=../tkbox || die "otcl-1.0a6 configuration failed! Exiting ..."

if make 
then
	echo "otcl-1.0a6 has been installed successfully."
else
	echo "otcl-1.0a6 make failed! Exiting ..."
	echo "See http://www.isi.edu/nsnam/ns/ns-problems.html for problems"
	exit
fi


cd ../

# compile and install tclcl-1.0b10

cd ./tclcl-1.0b10

./configure --with-tcl=../tclbox --with-tk=../tkbox || die "tclcl-1.0b10 configuration failed! Exiting ..."

if make
then
	echo "tclcl-1.0b10 has been installed successfully."
else
	echo "tclcl-1.0b10 make failed! Exiting ..."
	echo "See http://www.isi.edu/nsnam/ns/ns-problems.html for problems"
	exit
fi	


cd ../

#compile and install xgraph

cd ./xgraph-12.1
./configure --prefix=../
if make
then
	echo "xgraph has been installed successfully. "
else 
	echo "Can not create xgraph; But xgraph is an optional package, continuing..."
fi

cd ../

#compile and install cweb and sgblib

cd ./cweb

if [ ! -f ./Makefile ]
then
	echo "ns-allinone unable to install cweb for you. Please install it manually. cweb is used by sgb to create sgblibrary needed by scenario-generator. But this will not affect the use of ns as such, so continue.."
else
	echo "Making cweb"
	touch *.c
	make all || warn "cweb failed to make, but it's optional"
	# xxx: other stuff will fail...
	chmod 755 cweave
	chmod 755 ctangle
	cd ..
	#echo "cd .."
	if [ ! -d bin ]
	then
		mkdir bin
	fi
	cd bin
	ln -s $CUR_PATH/cweb/cweave cweave
	ln -s $CUR_PATH/cweb/ctangle ctangle
	
fi

cd ..
PATH=$CUR_PATH/bin:$PATH
export PATH
#echo $PATH

cd ./sgb
if [ ! -f ./Makefile ]
	then
	echo "Unable to create sgb library. This library is used by gt-itm and so for scenario generators. If you already have sgblib (possible if you are on solaris,sunos or freebsd platforms) you may still be able to run gt-itm. so continuing.."
else
	echo "Making sgb"
	if make tests
	then
		if [ -f lib*.a ]
		then
			if [ -f ../gt-itm/lib/libgb.a ]
			then
				rm ../gt-itm/lib/libgb.a
				cp lib*.a ../gt-itm/lib/libgb.a
			fi
		fi
	else
		echo "Unable to create sgb library, but it's optional, so continuing..."
	fi
fi

cd ..

# compile and install gt-itm & sgb2ns

## don't need to do this any longer
##./tclbox/bin/tclsh8.0.4 ./bin/gtitm.tcl

if [ -f ./gt-itm/lib/libgb.a ]
then
 if [ ! -f ./gt-itm/src/Makefile ] 
    then
    echo "ns-alline is unable to install gt-itm sgb2ns for you, please install"
    echo "them manually. You can't run scenario generator without gt-itm"
    echo "and sgb2ns. But it will not affect you use ns, so continue ..."
 else
    cd ./gt-itm/src
    if make
    then
      echo "gt-itm has been installed successfully."
    fi
    
    cd ../sgb2ns
    if make
    then
      echo "sgb2ns has been installed successfully."
    fi
   cd ../../

 fi
else
    echo "sgb lib not found. gt-itm & sgb2ns could not be installed. Continuing.."
fi

# Compile and install ns. Since ns searches for tclsh in $PATH, the following is needed.
PATH=$CUR_PATH/tclbox/bin:$CUR_PATH/tkbox/bin:$PATH
export PATH

# John's hack
test -f ./otcl-1.0a6/libotcl.a && rm ./otcl-1.0a6/libotcl.so

cd ./ns-2.1b7
./configure --with-tcl=../tclbox --with-tk=../tkbox || die "Ns configuration failed! Exiting ..."

if make
then
	echo " Ns has been installed successfully." 
else
	echo "Ns make failed!"
	echo "See http://www-mash.CS.Berkeley.EDU/ns/ns-problems.html for problems"
	exit
fi


cd ../

#compile and install zlib

cd ./zlib-1.1.3

if ./configure --exec-prefix=../ --prefix=../
then
	if make
	then
		echo "Zlib has been installed successfully."
	else
		warn "Zlib make failed, but it's optional Continue ..."
	fi
else
	warn "Zlib-1.1.3 configuration failed, but it's optional, so continuing ..."
fi

cd ../

#compile and install nam

cd ./nam-1.0a9

./configure --with-tcl=../tclbox --with-tk=../tkbox || die "Nam configuration failed! Exiting ..."

if make
then 
    echo "Nam has been installed successfully."
else
    echo "Nam make failed! Continue ..."
    echo "See http://www.isi.edu/nsnam/ns-problems.html for problems"
fi

cd ../

# install nam, ns, xgraph into bin

if [ ! -d bin ]
then
mkdir bin
fi

cd bin

ln -s $CUR_PATH/ns-2.1b7/ns ns

if test -x $CUR_PATH/nam-1.0a9/nam
then
    ln -s $CUR_PATH/nam-1.0a9/nam nam
else
    echo "Please compile your nam separately."
fi

if test -x $CUR_PATH/xgraph-12.1/xgraph
then
    ln -s $CUR_PATH/xgraph-12.1/xgraph xgraph
else
    echo "Please compile your xgraph separately."
fi

if test -x $CUR_PATH/gt-itm/bin/sgb2ns
then 
    ln -s $CUR_PATH/gt-itm/bin/sgb2ns sgb2ns
    ln -s $CUR_PATH/gt-itm/bin/sgb2hierns sgb2hierns
    ln -s $CUR_PATH/gt-itm/bin/sgb2comns sgb2comns
    ln -s $CUR_PATH/gt-itm/bin/itm itm
    ln -s $CUR_PATH/gt-itm/bin/sgb2alt sgb2alt
    ln -s $CUR_PATH/gt-itm/bin/edriver edriver
else
    echo "Please compile your gt-itm & sgb2ns separately."
fi

echo "Ns-allinone package has been installed successfully."
echo "Here are the installation places:"
echo "ns:	$CUR_PATH/ns-2.1b7/ns"
echo "otcl:	$CUR_PATH/otcl-1.0a6"
echo "tclcl:	$CUR_PATH/tclcl-1.0b10"
echo "tcl8.3.2:	$CUR_PATH/tclbox"
echo "tk8.3.2:	$CUR_PATH/tkbox"

if [ -x $CUR_PATH/nam-1.0a9/nam ]
then
echo "nam:	$CUR_PATH/nam-1.0a9/nam"
fi

if [ -x $CUR_PATH/xgraph-12.1/xgraph ]
then
echo "xgraph:	$CUR_PATH/xgraph-12.1"
fi
if [ -x $CUR_PATH/gt-itm/bin/sgb2ns ] 
then
echo "gt-itm:   $CUR_PATH/itm, edriver, sgb2alt, sgb2ns, sgb2comns, sgb2hierns"
fi

echo ""
echo "You can delete $CUR_PATH/tcl8.3.2 and $CUR_PATH/tk8.3.2 if "
echo "you want save your disk space"

echo "-----------------------------------------------------"
echo "Please put $CUR_PATH/bin into your PATH environment."
echo ""
echo "You MUST put $CUR_PATH/otcl-1.0a6, $CUR_PATH/tclbox/lib, $CUR_PATH/tkbox/lib"
echo "into your LD_LIBRARY_PATH environment variable. If it complains about X libraries,"
echo "add path to your X libraries into LD_LIBRARY_PATH."
echo ""
echo "You can run the ns validation suite with"
echo "cd ns-2.1b7; ./validate"

exit 0

